### ISSUE TITLE
Diccionario subido

### ISSUE THREAD

**Issue by florianRM** [florianRM/ProgramacionGIT#3]
Ya he subido el diccionario sin hashmap y con hashmap

**Comment by ioliasa** [comment]
Tienes que asingarme el Issues porque si no, no me llega notificación.

En addDicionario (el de listas) es más fácil buscar la letra que recorrerla entera, 

Falta el buscar el significado de una palabra y el buscar palabras que empiecen por

**Comment by florianRM** [comment]
Ya he añadido los 2 métodos que faltaban
